#!/usr/bin/env ruby

require "bundler/setup"
require "cleon"
extend Cleon::CLI

COMMAND = %w(clone service entity)
args = ARGV.map(&:downcase)
banner if args.empty?
command = args.shift

if command == 'clone'
  clone(Dir.pwd)
  exit
end

if command == 'entity'
  entity(args.join(' '), Dir.pwd)
  exit
end

if command == 'service'
  service(args.join(' '), Dir.pwd)
  exit
end

banner
