#!/usr/bin/env ruby

require "bundler/setup"
require "cleon"

usage = <<~EOF
  -= Cleon =- is a code skeleton of services and entities
  For more information visit https://github.com/nvoynov/cleon

  To clone cleon skeleton inside your gem:
  1. add `gem "cleon"` to your Gemfile
  2. run `$ cleon clone`
EOF

cmd = ARGV.shift
unless cmd && cmd.downcase == 'clone'
  puts usage
  exit
end

begin
  Cleon.clone_cleon(Dir.pwd)
rescue Cleon::Error => e
  puts e.message
end
